#-------------------------------------------------
#
# Project created by QtCreator 2017-07-16T22:07:36
#
#-------------------------------------------------

QT       += core gui sql printsupport
QT       += network charts concurrent
QT       += serialport
CONFIG   += release c++11

include(qtxlsx/src/xlsx/qtxlsx.pri)
#include(components/components.pri)
include(QtService/qtservice.pri)
#include(qtnotify/qtnotify.pri)

VERSION = 1.0.1.11

#win32 {
#    RC_FILE = algoERP.rc
#}

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = algoERP
TEMPLATE = app
TRANSLATIONS += lang_ar.ts

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

DEFINES += APP_VERSION=\\\"$$VERSION\\\"

#INCLUDEPATH += $$quote($$pwd\poppler-0.24.5-win32\poppler-0.24.5-win32\include\poppler-qt5)
#LIBS += -L$$quote($$pwd\poppler-0.24.5-win32\poppler-0.24.5-win32\lib) -lpoppler-qt5
LIBS += -lKernel32 -lwinspool

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
RC_ICONS = resources/gm.ico

SOURCES += \
    CommonUi/Transactions/InventoryLedger/inventoryledgertransactionseditor.cpp \
    CommonUi/Transactions/InventoryLedger/op.cpp \
    CommonUi/Transactions/vouchereditorbase.cpp \
    CommonUi/maintabwidget.cpp \
    CommonUi/mainwindowdrawerbuilder.cpp \
    CommonUi/mainworkarea.cpp \
    CommonUi/masterseditor.cpp \
    CommonUi/reportsselector.cpp \
    CommonUi/reportwidget.cpp \
    CommonUi/sidebar.cpp \
    CommonUi/uicontroller.cpp \
    CommonUi/uimain.cpp \
    Notifications/notificationshistory.cpp \
    SysServices/GMSync/gmsynchelper.cpp \
    SysServices/GMSync/myservice.cpp \
    SysServices/GMSync/qreplytimeout.cpp \
    SysServices/tabservice.cpp \
    counter/MainScreen/godownallocationwidget.cpp \
    counter/MainScreen/itemdetail.cpp \
    counter/MainScreen/itempricedetailswidget.cpp \
    counter/MainScreen/modeofservicewidget.cpp \
    counter/MainScreen/salesitemsgrid.cpp \
    counter/MainScreen/shiftentrywidget.cpp \
    counter/MainScreen/shiftvalueseditor.cpp \
    counter/Reports/Restaurant/itemtrasactionlist.cpp \
    counter/Reports/waiterwiseservicewisereport.cpp \
    counter/Shift/dailyclosingreport.cpp \
    counter/Shift/dailyreportcalculator.cpp \
    Notifications/notificationledgerslist.cpp \
    counter/MainScreen/customerscreen.cpp \
    counter/MainScreen/modeofpaystore.cpp \
    counter/MainScreen/paymentsplitwidget.cpp \
    counter/MainScreen/selectitemswidget.cpp \
    counter/Shift/restaurantshiftentry.cpp \
    counter/TableManagement/tablereservationeditor.cpp \
    counter/TableManagement/tablesmastereditor.cpp \
    customwidgets/Basic/Material/gmmaterialcheckbox.cpp \
    customwidgets/Basic/Material/gmmaterialcombobox.cpp \
    customwidgets/Basic/Material/gmmateriallineedit.cpp \
    customwidgets/Basic/Material/gmmaterialnumberedit.cpp \
    customwidgets/Basic/gmcardwidget.cpp \
    customwidgets/Basic/gmdateedit.cpp \
    customwidgets/Basic/gmdatetimeedit.cpp \
    customwidgets/Basic/gmhovertoolbutton.cpp \
    customwidgets/Basic/gmlineedit.cpp \
    customwidgets/Basic/gmplaintextedit.cpp \
    customwidgets/Basic/gmtimeedit.cpp \
    customwidgets/Charts/Multiset/multisetbarcharthelper.cpp \
    customwidgets/Charts/SinglesSet/singlesetbarcharthelper.cpp \
    customwidgets/Charts/drilldownchart.cpp \
    customwidgets/Charts/drilldownslice.cpp \
    Notifications/notificationslist.cpp \
    customwidgets/Company/companyselectorwidget.cpp \
    customwidgets/Delegates/Attendance/gmattendancedelegate.cpp \
    customwidgets/Delegates/Contacts/contactnamesearchdelegate.cpp \
    customwidgets/Delegates/Inventory/gminventorylistitemdelegate.cpp \
    customwidgets/Delegates/Inventory/gminventorytransactiondelegate.cpp \
    customwidgets/Delegates/Inventory/groupwisesalesreportdelegate.cpp \
    customwidgets/Delegates/Inventory/possalesitemsdelegate.cpp \
    customwidgets/Delegates/Ledgers/gmledgertransactiondelegate.cpp \
    customwidgets/Delegates/Notifications/notificationsdelegate.cpp \
    customwidgets/Delegates/Orders/gmitemwiseordersdelegate.cpp \
    customwidgets/Delegates/Orders/pendingdeliverydelegate.cpp \
    customwidgets/Delegates/Orders/salesorderstimebasedreportdelegate.cpp \
    customwidgets/Delegates/Payslip/gmpayslipdelegate.cpp \
    customwidgets/Delegates/Reconciliation/gmbankreconciliationdelegate.cpp \
    customwidgets/Delegates/Shift/gmshiftdelegate.cpp \
    customwidgets/Delegates/StockEntry/stockentrydelegate.cpp \
    customwidgets/Delegates/StockJournal/stockjournaldelegate.cpp \
    customwidgets/Delegates/StockRequest/stockrequestdelegate.cpp \
    customwidgets/Delegates/WorkOrder/kotreportdelegate.cpp \
    customwidgets/Delegates/WorkOrder/workorderdelegate.cpp \
    customwidgets/Delegates/billwisemappingdelegate.cpp \
    customwidgets/Delegates/closingstockretdelegate.cpp \
    customwidgets/Delegates/dailyclosingdelegate.cpp \
    customwidgets/Delegates/daybookreportdelegate.cpp \
    customwidgets/Delegates/itemchecklistdelegate.cpp \
    customwidgets/Delegates/itemmovementanalysisdelegate.cpp \
    customwidgets/Delegates/registerdelegate.cpp \
    customwidgets/Delegates/reportwithextracolumndelegate.cpp \
    customwidgets/Delegates/salesordersdelgate.cpp \
    customwidgets/Delegates/userpermissionsdelegate.cpp \
    customwidgets/Fifo/fifopopupdialog.cpp \
    customwidgets/Material/components/layouts/qtmaterialsnackbarlayout.cpp \
    customwidgets/Material/components/lib/qtmaterialcheckable.cpp \
    customwidgets/Material/components/lib/qtmaterialcheckable_internal.cpp \
    customwidgets/Material/components/lib/qtmaterialoverlaywidget.cpp \
    customwidgets/Material/components/lib/qtmaterialripple.cpp \
    customwidgets/Material/components/lib/qtmaterialrippleoverlay.cpp \
    customwidgets/Material/components/lib/qtmaterialstatetransition.cpp \
    customwidgets/Material/components/lib/qtmaterialstyle.cpp \
    customwidgets/Material/components/lib/qtmaterialtheme.cpp \
    customwidgets/Material/components/qtmaterialappbar.cpp \
    customwidgets/Material/components/qtmaterialautocomplete.cpp \
    customwidgets/Material/components/qtmaterialautocomplete_internal.cpp \
    customwidgets/Material/components/qtmaterialavatar.cpp \
    customwidgets/Material/components/qtmaterialbadge.cpp \
    customwidgets/Material/components/qtmaterialcheckbox.cpp \
    customwidgets/Material/components/qtmaterialcircularprogress.cpp \
    customwidgets/Material/components/qtmaterialcircularprogress_internal.cpp \
    customwidgets/Material/components/qtmaterialdialog.cpp \
    customwidgets/Material/components/qtmaterialdialog_internal.cpp \
    customwidgets/Material/components/qtmaterialdrawer.cpp \
    customwidgets/Material/components/qtmaterialdrawer_internal.cpp \
    customwidgets/Material/components/qtmaterialfab.cpp \
    customwidgets/Material/components/qtmaterialflatbutton.cpp \
    customwidgets/Material/components/qtmaterialflatbutton_internal.cpp \
    customwidgets/Material/components/qtmaterialiconbutton.cpp \
    customwidgets/Material/components/qtmateriallist.cpp \
    customwidgets/Material/components/qtmateriallistitem.cpp \
    customwidgets/Material/components/qtmaterialmenu.cpp \
    customwidgets/Material/components/qtmaterialmenu_internal.cpp \
    customwidgets/Material/components/qtmaterialpaper.cpp \
    customwidgets/Material/components/qtmaterialprogress.cpp \
    customwidgets/Material/components/qtmaterialprogress_internal.cpp \
    customwidgets/Material/components/qtmaterialradiobutton.cpp \
    customwidgets/Material/components/qtmaterialraisedbutton.cpp \
    customwidgets/Material/components/qtmaterialscrollbar.cpp \
    customwidgets/Material/components/qtmaterialscrollbar_internal.cpp \
    customwidgets/Material/components/qtmaterialslider.cpp \
    customwidgets/Material/components/qtmaterialslider_internal.cpp \
    customwidgets/Material/components/qtmaterialsnackbar.cpp \
    customwidgets/Material/components/qtmaterialsnackbar_internal.cpp \
    customwidgets/Material/components/qtmaterialtable.cpp \
    customwidgets/Material/components/qtmaterialtabs.cpp \
    customwidgets/Material/components/qtmaterialtabs_internal.cpp \
    customwidgets/Material/components/qtmaterialtextfield.cpp \
    customwidgets/Material/components/qtmaterialtextfield_internal.cpp \
    customwidgets/Material/components/qtmaterialtoggle.cpp \
    customwidgets/Material/components/qtmaterialtoggle_internal.cpp \
    customwidgets/Misc/customshadoweffect.cpp \
    customwidgets/Misc/getschedule.cpp \
    customwidgets/Misc/gmcpbar.cpp \
    customwidgets/Misc/hashtagedit.cpp \
    customwidgets/Misc/hashtaglinewidget.cpp \
    customwidgets/Misc/loading.cpp \
    customwidgets/Misc/sidebarbutton.cpp \
    customwidgets/Models/gmaccesscontrolmodel.cpp \
    customwidgets/Models/gmbillwisemappingmodel.cpp \
    customwidgets/Models/gmemployeemodel.cpp \
    customwidgets/Models/gmfifomodel.cpp \
    customwidgets/Models/gmgodownallocationmodel.cpp \
    customwidgets/Models/gmgodowntransfermodel.cpp \
    customwidgets/Models/gminventoryitemmodel.cpp \
    customwidgets/Models/gmitemchecklistmodel.cpp \
    customwidgets/Models/gmitemwiseordermodel.cpp \
    customwidgets/Models/gmjournalentrymodel.cpp \
    customwidgets/Models/gmledgeritemmodel.cpp \
    customwidgets/Models/gmnotificationlistmodel.cpp \
    customwidgets/Models/gmpaymententrymodel.cpp \
    customwidgets/Models/gmpayslipmodel.cpp \
    customwidgets/Models/gmreceiptentrymodel.cpp \
    customwidgets/Models/gmreconciliationmodel.cpp \
    customwidgets/Models/gmshiftmodel.cpp \
    customwidgets/Models/gmshiftsalesmodel.cpp \
    customwidgets/Models/gmsqlquerymodel.cpp \
    customwidgets/Models/gmstockentrymodel.cpp \
    customwidgets/Models/gmstockinentrymodel.cpp \
    customwidgets/Models/gmstockjournalmodel.cpp \
    customwidgets/Models/gmstockrequestmodel.cpp \
    customwidgets/Models/gmwastageentrymodel.cpp \
    customwidgets/Models/gmworkordermodel.cpp \
    customwidgets/Models/possalesitemsmodel.cpp \
    customwidgets/SearchWidgets/AccountGroup/gmaccountgroupsearchwidget.cpp \
    customwidgets/SearchWidgets/Contact/gmcontactlinematerial.cpp \
    customwidgets/SearchWidgets/Employee/employeesearchdelegate.cpp \
    customwidgets/SearchWidgets/Employee/gmemployeelinematerial.cpp \
    customwidgets/SearchWidgets/Employee/gmemployeesearchline.cpp \
    customwidgets/SearchWidgets/Employee/gmemployeesearchlistwidgetlite.cpp \
    customwidgets/SearchWidgets/Employee/gmemployeesearchlite.cpp \
    customwidgets/SearchWidgets/Employee/gmemployeesearchproxymodel.cpp \
    customwidgets/SearchWidgets/Employee/gmemployeesearchwidget.cpp \
    customwidgets/SearchWidgets/Godown/gmgodownlinematerial.cpp \
    customwidgets/SearchWidgets/Godown/gmgodownsearchlistwidgetlite.cpp \
    customwidgets/TableViews/userpermissionstableview.cpp \
    customwidgets/appbarwidget.cpp \
    customwidgets/barcodeprintwidget.cpp \
    customwidgets/SearchWidgets/Godown/gmgodownsearchlite.cpp \
    customwidgets/SearchWidgets/Godown/gmgodownsearchproxymodel.cpp \
    customwidgets/SearchWidgets/Godown/godownsearchdelegate.cpp \
    customwidgets/SearchWidgets/InventoryGroup/gminventorygroupsearchwidget.cpp \
    customwidgets/SearchWidgets/Inventoryitem/Completer/gminventoryitemsearch.cpp \
#    customwidgets/SearchWidgets/Inventoryitem/gminventoryitemlinematerial.cpp \
    customwidgets/SearchWidgets/Ledger/gmledgerlinematerial.cpp \
    customwidgets/SearchWidgets/Ledger/gmledgerlinewidget.cpp \
    customwidgets/SearchWidgets/Pricelist/gmpricelistlinematerial.cpp \
    customwidgets/SearchWidgets/Uom/uomsearchwidget.cpp \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchlistwidgetlite.cpp \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchlite.cpp \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchproxymodel.cpp \
    customwidgets/SearchWidgets/Widgets/widgetsearchdelegate.cpp \
    customwidgets/TableViews/employeetableview.cpp \
    customwidgets/TableViews/inventoryvouchertableview.cpp \
    customwidgets/TableViews/itemwiseentrytableview.cpp \
    customwidgets/TableViews/ledgervouchertableview.cpp \
    customwidgets/TableViews/ledgerwisetableview.cpp \
    customwidgets/TableViews/paysliptableview.cpp \
    customwidgets/TableViews/reportstableview.cpp \
    customwidgets/TableViews/shiftsalestableview.cpp \
    customwidgets/TableViews/stockentrytableview.cpp \
    customwidgets/checklistpromptdialog.cpp \
    customwidgets/filterwidget.cpp \
    customwidgets/gmreportsortfilterproxymodel.cpp \
    customwidgets/godownselectorwidget.cpp \
    customwidgets/itemchecklistwidget.cpp \
    customwidgets/modeofservicebutton.cpp \
    customwidgets/showvoucherswidget.cpp \
    customwidgets/test/flowlayout.cpp \
    dashboard/accountsmaindashboard.cpp \
    dashboard/customerdashboard.cpp \
    dashboard/inventoryitemdashboard.cpp \
    dashboard/purchasesmaindash.cpp \
    dashboard/receiptsmaindash.cpp \
    dashboard/salesmaindash.cpp \
    database/Counter/TableManagement/tablereservationdatabasehelper.cpp \
    database/Counter/TableManagement/tablesmasterhelper.cpp \
    database/Reports/closingstockhelper.cpp \
    database/Reports/ledgerhelpermt.cpp \
    database/Settings/configsettingsvalues.cpp \
    database/Settings/configsettingsvariables.cpp \
    database/Settings/configurationsettingsdatabasehelper.cpp \
    database/Settings/uisettingsdatabasehelper.cpp \
    database/Settings/uisettingsvariables.cpp \
    database/databasehelper/bulkloaddatabasehelper.cpp \
    database/databasehelper/databaseupdater.cpp \
    database/finance/Closing/restaurantshiftdatabasehelper.cpp \
    database/finance/ItemTransaction/transactionfifodatabasehelper.cpp \
    database/finance/proforma/proformadatabasehelper.cpp \
    database/finance/salesvoucher/salesvoucherdeleteddatabasehelper.cpp \
    database/hr/attendancedatabasehelper.cpp \
    database/hr/payslipdatabasehelper.cpp \
    database/inventory/StockRequest/stockrequestdatabasehelper.cpp \
    database/inventory/category/categorydatabasehelper.cpp \
    database/inventory/defective/defectivedatabasehelper.cpp \
    database/inventory/godowntransfer/godowntransferdatabasehelper.cpp \
    database/inventory/inventorytemplate/inventorytemplatedatabasehelper.cpp \
    database/inventory/label/itemlabeldatabasehelper.cpp \
    database/inventory/receiptnote/receiptnotedatabasehelper.cpp \
    database/Notifications/receivechanneldatabasehelper.cpp \
    database/Notifications/sendchanneldatabasehelper.cpp \
    database/inventory/sales_inventory_items/bundledatabasehelper.cpp \
    database/inventory/salesorder/itemwisesalesorderdatabasehelper.cpp \
    database/inventory/workorder/workorderdatabasehelper.cpp \
    database/projects/hashtagdatabasehelper.cpp \
    database/voucherdbabstract.cpp \
    datamodels/Counter/denominationsdatamodel.cpp \
    datamodels/Counter/shiftledgersdatamodel.cpp \
    datamodels/Counter/tablemasterdatamodel.cpp \
    datamodels/Counter/tablereservationdatamodel.cpp \
    datamodels/Settings/licenseinfodatamodel.cpp \
    datamodels/Settings/uisettingsdatamodel.cpp \
    datamodels/godowns/godowntransactiondatamodel.cpp \
    datamodels/hr/attendancedatamodel.cpp \
    datamodels/hr/attendancelistdatamodel.cpp \
    datamodels/hr/employeesalarydatamodel.cpp \
    datamodels/hr/payslipdatamodel.cpp \
    datamodels/hr/uiaccesscontroldatamodel.cpp \
    datamodels/inventory/Label/itemlabeldatamodel.cpp \
    datamodels/inventory/category/categorydatamodel.cpp \
    datamodels/inventory/sales_inventory_item/inventoryitembatchmodel.cpp \
    datamodels/inventory/sales_inventory_item/skudatamodel.cpp \
    datamodels/sampleobjectdatamodel.cpp \
    datamodels/transaction/gmtaxclass.cpp \
    datamodels/transaction/gmvouchertypes.cpp \
    datamodels/transaction/itemfifodatamodel.cpp \
    datamodels/transaction/requirementvoucherdataobject.cpp \
    datamodels/utils/emailmodel.cpp \
    ecommerce/cartwidget.cpp \
    ecommerce/itemdetailwidget.cpp \
    ecommerce/itemselectorwidget.cpp \
    ecommerce/shippingdetailseditor.cpp \
    finance/reports/BankReconciliation/bankreconciliation.cpp \
    finance/reports/GSTReport/gstreport.cpp \
    finance/reports/GSTReport/hsnreportdelegate.cpp \
    finance/reports/GSTReport/vatreport.cpp \
    finance/reports/SalesOrders/deliveryordersmodel.cpp \
    finance/reports/SalesOrders/pendingorders.cpp \
    finance/reports/SalesOrders/pendingordersdelegate.cpp \
    finance/transactions/BillwiseRecords/billwisemappingeditor.cpp \
    finance/transactions/LedgerView/ledgerwisevouchertableview.cpp \
    finance/transactions/LedgerView/ledgerwisevoucherview.cpp \
    finance/transactions/Proforma/proformainvoiceeditor.cpp \
    finance/transactions/calculator/fifocalculator.cpp \
    finance/transactions/contra/contravouchereditor.cpp \
    finance/transactions/creditnote/creditnotevouchereditor.cpp \
    finance/transactions/debitnote/debitnotevouchereditor.cpp \
    finance/transactions/journals/journalvouchereditor.cpp \
    finance/transactions/payments/paymentvouchereditor.cpp \
    finance/transactions/purchases/purchasevouchereditor.cpp \
    finance/transactions/receipts/receiptvouchereditor.cpp \
    finance/transactions/sales/salesadjustmentwidget.cpp \
    finance/transactions/sales/salesvouchereditor.cpp \
    datamodels/Notification/notificationdatamodel.cpp \
    finance/transactions/sales/voucherrecalculater.cpp \
    hr/Reports/payslipreport.cpp \
    hr/addemployeesalarydetails.cpp \
    hr/attendanceeditor.cpp \
    hr/payslipgenerationeditor.cpp \
    hr/uacsortmodel.cpp \
    hr/usergrouppermissionseditor.cpp \
    inventory/masters/item_label_data/itemlabeldata.cpp \
    inventory/masters/sales_inventory_items/bundle/itembundlelistdelegate.cpp \
    inventory/masters/sales_inventory_items/bundle/itembundlelistmodel.cpp \
    inventory/masters/sales_inventory_items/bundle/itembundletableview.cpp \
    inventory/masters/sales_inventory_items/updateplulisttextfileclass.cpp \
    inventory/pricelist/pricelistbyitem.cpp \
    inventory/pricelist/pricelistdelegate.cpp \
    inventory/pricelist/pricelistmodel.cpp \
    inventory/pricelist/pricelistsortmodel.cpp \
    inventory/pricelist/pricelisttableview.cpp \
    inventory/reports/CreditNoteReport/creditnotereport.cpp \
    inventory/reports/DailyCosting/dailycostingreport.cpp \
    inventory/reports/DebitNoteReport/debitnotereport.cpp \
    inventory/reports/ItemwiseReport/itemwisesalesorderbymode.cpp \
    inventory/reports/MovementAnalysis/godownwiseitemmovement.cpp \
    inventory/reports/MovementAnalysis/groupwiseitemmovement.cpp \
    inventory/reports/MovementAnalysis/ledgerwiseitemmovement.cpp \
    inventory/reports/PurchaseReport/purchasereport.cpp \
    inventory/reports/WastageReport/wastagereport.cpp \
    inventory/reports/WorkOrderReport/kotreport.cpp \
    inventory/reports/WorkOrderReport/workorderreport.cpp \
    inventory/transactions/Defective/wastageentryeditor.cpp \
    inventory/transactions/InventoryTemplate/inventorytemplateeditor.cpp \
    inventory/transactions/InventoryTemplate/inventorytemplatelist.cpp \
    inventory/transactions/ItemwiseSalesOrder/additemwisesalesorder.cpp \
    inventory/transactions/ItemwiseSalesOrder/iteemwisesalesorderlist.cpp \
    inventory/transactions/ItemwiseSalesOrder/itemwisesodatewisereport.cpp \
    inventory/transactions/StockRequest/stockrequesteditor.cpp \
    inventory/transactions/deliverynote/deliverynoteeditor.cpp \
    inventory/transactions/materialinout/materialinouteditor.cpp \
    inventory/transactions/purchaseorders/purchaseordervouchereditor.cpp \
    inventory/transactions/receiptnotes/receiptnotevouchereditor.cpp \
    inventory/transactions/salesorders/salesordervouchereditor.cpp \
    inventory/transactions/stockentry/stockentryeditor.cpp \
    inventory/transactions/stockjournal/stockjournaleditor.cpp \
        main.cpp \
        mainwindow.cpp \
    database/databasehelper/databasehelper.cpp \
    database/inventory/sales_inventory_groups/salesinventorygroupsdatabasehelper.cpp \
    database/inventory/sales_inventory_items/salesinventoryitemdatabasehelper.cpp \
    datamodels/inventory/sales_inventory_item/inventoryitemdatamodel.cpp \
    datamodels/inventory/sales_inventory_group/inventoryitemgroupdatamodel.cpp \
    datamodels/accounts/ledgermasterdatamodel.cpp \
    datamodels/accounts/accountgroupdatamodel.cpp \
    datamodels/inventory/property/propertydatamodel.cpp \
    datamodels/inventory/sales_inventory_item/compounditemdataobject.cpp \
    datamodels/inventory/uom/uomdatamodel.cpp \
    datamodels/inventory/pricelist/pricelistdataobject.cpp \
    datamodels/transaction/salestransactiondatamodel.cpp \
    datamodels/transaction/generalvoucherdataobject.cpp \
    database/databasehelper/databasevalues.cpp \
    database/finance/ledgermaster/ledgermasterdatabasehelper.cpp \
    database/finance/accountmaster/accountgroupmasterdatabasehelper.cpp \
    database/finance/salesvoucher/salesvoucherdatabasehelper.cpp \
    database/finance/purchasevoucher/purchasevoucherdatabasehelper.cpp \
    database/finance/receiptvoucher/receiptvoucherdatabasehelper.cpp \
    database/finance/paymentvoucher/paymentvoucherdatabasehelper.cpp \
    database/finance/creditnote/creditnotevoucherdatabasehelper.cpp \
    database/finance/debitnote/debitnotevoucherdatabasehelper.cpp \
    database/finance/contra/contravoucherdatabasehelper.cpp \
    database/inventory/pricelist/pricelistdatabasehelper.cpp \
    database/inventory/uom/uomdatabasehelper.cpp \
    database/inventory/salesorder/salesorderdatabasehelper.cpp \
    database/inventory/purchaseorder/purchaseorderdatabasehelper.cpp \
    database/inventory/deliverynote/deliverynotedatabasehelper.cpp \
    database/inventory/quotation/quotationdatabasehelper.cpp \
    database/inventory/property/propertydatabasehelper.cpp \
    database/inventory/materialinout/materialinoutdatabasehelper.cpp \
    database/inventory/stockentry/stockentrydatabasehelper.cpp \
    database/inventory/stockjournal/stockjournaldatabasehelper.cpp \
    datamodels/inventory/godown/godowndataobject.cpp \
    database/inventory/godown/godowndatabasehelper.cpp \
    datamodels/accounts/transactionreferenceobject.cpp \
    datamodels/accounts/chequedetail.cpp \
    datamodels/accounts/ledgerdetaildatamodel.cpp \
    customwidgets/section.cpp \
    customwidgets/gmcombobox.cpp \
    customwidgets/gmsearchlineedit.cpp \
    folder/lineediticon.cpp\
    datamodels/projects/projectsdataobject.cpp \
    datamodels/projects/projecttaskdataobject.cpp \
    datamodels/users/userprofiledataobject.cpp \
    customwidgets/sharebutton.cpp \
    projects/WorkOrder/workordereditor.cpp \
    projects/WorkOrder/workordergenerator.cpp \
    projects/WorkOrder/workorderlist.cpp \
    projects/quotations/quotaitonslist.cpp \
    projects/quotations/quotationeditor.cpp \
    sharetools/email/emailthread.cpp \
    sharetools/email/emailwidget.cpp \
    sharetools/pdf/pdfhelper.cpp \
    sharetools/print/printdotmatrix.cpp \
    sharetools/print/printoptions.cpp \
    sharetools/print/voucherprinter.cpp \
    sharetools/sharetools.cpp \
    sharetools/email/email.cpp \
    sharetools/excel/excel.cpp \
    customwidgets/defaultdashboard.cpp \
    projects/projects.cpp \
    projects/requirements/requirementslist.cpp \
    customwidgets/lineedittest.cpp \
    datamodels/addressbook/addressbookdatamodel.cpp \
    database/addressBook/addressbookdatabasehelper.cpp \
    finance/masters/accountgroups/addaccountgroup.cpp \
    inventory/masters/uom/addconversion.cpp \
    inventory/masters/uom/adduom.cpp \
    sharetools/sms/smswidget.cpp \
    utils/AppUpdater/Downloader.cpp \
    utils/AppUpdater/QSimpleUpdater.cpp \
    utils/AppUpdater/Updater.cpp \
    utils/AppUpdater/appupdater.cpp \
    utils/DatabaseUpdater/configdbupdater.cpp \
    utils/DatabaseUpdater/databaseupdaterwidget.cpp \
    utils/DatabaseUpdater/dbbackuphelper.cpp \
    utils/License/licensechecker.cpp \
    utils/QRCodeGenerator/qrcode.cpp \
    utils/SettingsHelper/settingshelper.cpp \
    utils/duplicateitemsdialog.cpp \
    utils/gmfileuploadhelper.cpp \
    utils/itemsynctool.cpp \
    utils/logger.cpp \
    utils/logincontroller.cpp \
    voucherOperations/VocuherList/templatelist.cpp \
    voucherOperations/VoucherEditor/vouchereditor.cpp \
    voucherOperations/coupledvoucherhandler.cpp \
    voucherOperations/vouchereditorselector.cpp \
    warehouse/godowntransfer/godowntransfereditor.cpp \
    warehouse/godowntransfer/godowntransfer.cpp \
    addressbook/addressbook.cpp \
    addressbook/adressbook_display.cpp \
    finance/masters/ledgers/addledger.cpp \
    inventory/masters/godowns/addgodown.cpp \
    inventory/masters/properties/addproperty.cpp \
    inventory/masters/properties/propertylist.cpp \
    inventory/masters/sales_inventory_groups/additemgroups.cpp \
    inventory/masters/sales_inventory_items/additemprice.cpp \
    inventory/masters/sales_inventory_items/additems.cpp \
    inventory/pricelist/addpricelist.cpp \
    projects/quotations/addquotation.cpp \
    projects/quotations/quotations.cpp \
    projects/requirements/additemadditionalrequirement.cpp \
    projects/requirements/additemrequirement.cpp \
    projects/requirements/requirement.cpp \
    projects/addproject.cpp \
    projects/projectwidget.cpp \
    addressbook/contacts_sidebar.cpp \
    dashboard/dashboard_sidebar.cpp \
    helpdesk/helpdesk_sidebar.cpp \
    projects/projects_sidebar.cpp \
    services/services_sidebar.cpp \
    toolbar/maintoolbar.cpp \
    toolbar/utilities_toolbar.cpp \
    inventory/masters/brands/addbrands.cpp \
    datamodels/inventory/brands/brandsdatamodel.cpp \
    database/inventory/brands/brandsdatabasehelper.cpp \
    database/projects/requirementsdatabasehelper.cpp \
    datamodels/addressbook/employeeaddressdatamodel.cpp \
    customwidgets/customitemview.cpp \
    customwidgets/ledgercompletertablemodel.cpp \
    customwidgets/listviewdelegate.cpp \
    sharetools/print/printerhelper.cpp \
    database/projects/projectsdatabasehelper.cpp \
    customwidgets/gmitemsearch.cpp \
    customwidgets/searchlistitemwidget.cpp \
    customwidgets/gmlistwidget.cpp \
    customwidgets/gmitemsearchwidget.cpp \
    customwidgets/gmsearchledgerwidgetitem.cpp \
    customwidgets/gmledgersearch.cpp \
    customwidgets/gmledgersearchwidget.cpp \
    projects/quotations/quotationdetails.cpp \
    database/finance/journalvoucher/journalvoucherdatabasehelper.cpp \
    hr/adduserprofile.cpp \
    finance/masters/termsconditions/termsconditions.cpp \
    database/finance/terms/termsdatabasehelper.cpp \
    finance/reports/LedgerReport/ledgerreport.cpp \
    database/hr/usergroupdatabasehelper.cpp \
    database/hr/userprofiledatabasehelper.cpp \
    datamodels/hr/usergroupdatamodel.cpp \
    datamodels/hr/userprofiledatamodel.cpp \
    customwidgets/form.cpp \
    customwidgets/importvoucherlist.cpp \
    database/inventory/sales_inventory_items/inventoryitemimagesdatabasehelper.cpp \
    datamodels/inventory/sales_inventory_item/itemimagedatamodel.cpp \
    datamodels/addressbook/addressbooksmall.cpp \
    login/loginpage.cpp \
    login/loginvalues.cpp \
    customwidgets/ContactSearch/gmcontactsearchwidget.cpp \
    customwidgets/ContactSearch/contactlistwidgetitem.cpp \
    customwidgets/ContactSearch/gmcontactsearch.cpp \
    database/projects/oldquote/oldquotationdatabasehelper.cpp \
    projects/Draftsman/draftsmanview.cpp \
    projects/Draftsman/quoteview.cpp \
    projects/Draftsman/itemdetailview.cpp \
    datamodels/projects/Documents/documentsdatamodel.cpp \
    datamodels/Documents/documentdatamodel.cpp \
    projects/History/previousquotationslist.cpp \
    projects/History/previousquotationwidget.cpp \
    datamodels/projects/Quotation/quotationstatus.cpp \
    projects/Documents/documentslist.cpp \
    projects/WorkOrder/workorderitemdetail.cpp \
    projects/WorkOrder/workorderquotes.cpp \
    projects/PendingApprovals/pendingapprovalslist.cpp \
    counter/MainScreen/denominations.cpp \
    counter/Shift/shiftentry.cpp \
    counter/Reports/billwisereport.cpp \
    counter/Reports/reportsmainwindow.cpp \
    counter/Shift/closingentry.cpp \
    counter/MainScreen/addressdialog.cpp \
    counter/Reports/timebasedsales.cpp \
    counter/MainScreen/restuarantcountermainwindow.cpp \
    finance/reports/TrialBalance/trialbalance.cpp \
    finance/reports/ProfitAndLossReport/profitandlossreport.cpp \
    finance/reports/BalanceSheet/balancesheet.cpp \
    datamodels/projects/Quotation/documenttype.cpp \
    customwidgets/Bank/chequewidget.cpp \
    database/finance/reports/reportsdatabasehelper.cpp \
    purchases/reports/ItemsReserved/itemsreserved.cpp \
    purchases/reports/CostEstimates/costestimates.cpp \
    customwidgets/numberpad.cpp \
    counter/MainScreen/modeofpay.cpp \
    database/Reports/ledgerhelper.cpp \
    database/Reports/inventoryhelper.cpp \
    inventory/reports/GroupwiseReport/groupwisereport.cpp \
    counter/PrinterHelper/counterprinterhelper.cpp \
    datamodels/Counter/servicemode.cpp \
    counter/Reports/todaysbills.cpp \
    counter/Settings/settings.cpp \
    counter/Settings/about.cpp \
    counter/Settings/helpcontents.cpp \
    datamodels/Counter/shiftdatamodel.cpp \
    database/finance/Closing/shiftdatabasehelper.cpp \
    addressbook/companyprofilewidget.cpp \
    database/addressBook/companyprofiledatabasehelper.cpp \
    datamodels/addressbook/companyprofiledatamodel.cpp \
    counter/MainScreen/assignsalesman.cpp \
    customwidgets/qtbutton.cpp \
    datamodels/Counter/countersettingsdatamodel.cpp \
    database/Counter/countersettingsdatabasehelper.cpp \
    services/Transactions/serviceregistrationwidget.cpp \
    services/Transactions/serviceregisterlist.cpp \
    database/Service/seviceregisterdatabasehelper.cpp \
    datamodels/Services/servicecomplaintregisterdatamodel.cpp \
    datamodels/Services/servicestatus.cpp \
    datamodels/Services/complaintlogdatamodel.cpp \
    datamodels/inventory/salesinventoryitemstablemodel.cpp \
    counter/MainScreen/restaurantextras.cpp \
    counter/MainScreen/passwordentry.cpp \
    counter/MainScreen/tableselect.cpp \
    counter/MainScreen/salesitems.cpp \
    counter/MainScreen/salesgroups.cpp \
    database/finance/ItemTransaction/itemtransactiondatabasehelper.cpp \
    datamodels/transaction/itemtransactiondatamodel.cpp \
    datamodels/Services/servicecomplaintdescriptionmodel.cpp \
    counter/Reports/shiftwisereport.cpp \
    counter/Reports/dailyclosingsalesreport.cpp \
    counter/Reports/waiterwisesalesreport.cpp \
    counter/Reports/modeofservicewisereport.cpp \
    counter/Reports/complimentarysalesreport.cpp \
    counter/Reports/discountsreport.cpp \
    database/finance/TransactionHelper/transactionhelper.cpp \
    customwidgets/mydelegate.cpp \
    customwidgets/test/testform.cpp \
    customwidgets/test/gmitemsortfilterproxymodel.cpp \
    customwidgets/test/ledgerreportdelegate.cpp \
    database/Counter/billofmaterialsingredientsdatabasehelper.cpp \
    datamodels/Counter/restaurantingredientsdatamodel.cpp \
    counter/MainScreen/miscellaneousitems.cpp \
    customwidgets/Delegates/itemwisesalesdelegate.cpp \
    customwidgets/Delegates/reportcommondelegate.cpp \
    sharetools/email/SMTP/gmail/smtp.cpp \
    counter/Reports/Restaurant/restaurantsalesordersreport.cpp \
    counter/Reports/Restaurant/restaurantdeliveryreport.cpp \
    counter/Reports/Restaurant/restaurantpendingdelivery.cpp \
    counter/Reports/Restaurant/restaurantsaveddrafts.cpp \
    counter/Reports/Restaurant/zomatoreport.cpp \
    customwidgets/test/itemcompleter.cpp \
    database/Reports/vatreportdatabasehelper.cpp \
    counter/Settings/kotprintersettings.cpp \
    customwidgets/Delegates/trialbalancedelegate.cpp \
    customwidgets/Crypto/simplecrypt.cpp \
    counter/Reports/Restaurant/restaurantclosingstock.cpp \
    database/finance/Closing/dailyclosingdatabasehelper.cpp \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchlite.cpp \
    customwidgets/SearchWidgets/Inventoryitem/itemsearchdelegate.cpp \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchproxymodel.cpp \
    counter/MainScreen/restaurantitemdetail.cpp \
    inventory/masters/sales_inventory_items/salesinventoryopening.cpp \
    finance/masters/ledgers/ledgeropeningvalues.cpp \
    customwidgets/Delegates/todaysbillsdelegate.cpp \
    sharetools/excel/excelreporthelper.cpp \
    customwidgets/Delegates/billwisereportdelegate.cpp \
    datamodels/inventory/uom/uomconversiondatamodel.cpp \
    customwidgets/Delegates/salesmarginreportdelegate.cpp \
    database/finance/BillwiseRecords/billwiserecordsdatabasehelper.cpp \
    datamodels/transaction/billwiserecorddatamodel.cpp \
    finance/transactions/BillwiseRecords/addbillwiserecord.cpp \
    database/finance/banking/chequedetailsdatabasehelper.cpp \
    customwidgets/SearchWidgets/Ledger/gmledgersearchlite.cpp \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchlistwidgetlite.cpp \
    customwidgets/SearchWidgets/Ledger/gmledgersearchlistwidgetlite.cpp \
    customwidgets/SearchWidgets/Ledger/gmledgersearchproxymodel.cpp \
    customwidgets/SearchWidgets/Ledger/gmledgersearchdelegate.cpp \
    finance/transactions/calculator/transactioncalculator.cpp \
    customwidgets/LedgersView/ledgersdisplaycontroller.cpp \
    customwidgets/LedgersView/gmtablewidgetledger.cpp \
    customwidgets/Notifications/qnotify.cpp \
    database/finance/TransactionHelper/generalvoucherdatabasehelper.cpp \
    database/Reports/accountingreportdatabasehelper.cpp \
    webservices/test/webservicetestsms.cpp

HEADERS += \
    CommonUi/Transactions/InventoryLedger/inventoryledgertransactionseditor.h \
    CommonUi/Transactions/InventoryLedger/op.h \
    CommonUi/Transactions/vouchereditorbase.h \
    CommonUi/maintabwidget.h \
    CommonUi/mainwindowdrawerbuilder.h \
    CommonUi/mainworkarea.h \
    CommonUi/masterseditor.h \
    CommonUi/reportsselector.h \
    CommonUi/reportwidget.h \
    CommonUi/sidebar.h \
    CommonUi/uicontroller.h \
    CommonUi/uimain.h \
    Notifications/notificationshistory.h \
    SysServices/GMSync/gmsynchelper.h \
    SysServices/GMSync/myservice.h \
    SysServices/GMSync/qreplytimeout.h \
    SysServices/GMSync/sleep.h \
    SysServices/tabservice.h \
    counter/MainScreen/godownallocationwidget.h \
    counter/MainScreen/itempricedetailswidget.h \
    counter/MainScreen/modeofservicewidget.h \
    counter/MainScreen/salesitemsgrid.h \
    counter/MainScreen/shiftentrywidget.h \
    counter/MainScreen/shiftvalueseditor.h \
    counter/Reports/Restaurant/itemtrasactionlist.h \
    counter/Reports/waiterwiseservicewisereport.h \
    counter/Shift/dailyclosingreport.h \
    counter/Shift/dailyreportcalculator.h \
    Notifications/notificationledgerslist.h \
    counter/MainScreen/customerscreen.h \
    counter/MainScreen/modeofpaystore.h \
    counter/MainScreen/paymentsplitwidget.h \
    counter/MainScreen/selectitemswidget.h \
    counter/Shift/restaurantshiftentry.h \
    counter/TableManagement/tablereservationeditor.h \
    counter/TableManagement/tablesmastereditor.h \
    customwidgets/Basic/Material/gmmaterialcheckbox.h \
    customwidgets/Basic/Material/gmmaterialcombobox.h \
    customwidgets/Basic/Material/gmmateriallineedit.h \
    customwidgets/Basic/Material/gmmaterialnumberedit.h \
    customwidgets/Basic/gmcardwidget.h \
    customwidgets/Basic/gmdateedit.h \
    customwidgets/Basic/gmdatetimeedit.h \
    customwidgets/Basic/gmhovertoolbutton.h \
    customwidgets/Basic/gmlineedit.h \
    customwidgets/Basic/gmplaintextedit.h \
    customwidgets/Basic/gmtimeedit.h \
    customwidgets/Charts/Multiset/multisetbarcharthelper.h \
    customwidgets/Charts/SinglesSet/singlesetbarcharthelper.h \
    customwidgets/Charts/drilldownchart.h \
    customwidgets/Charts/drilldownslice.h \
    Notifications/notificationslist.h \
    customwidgets/Company/companyselectorwidget.h \
    customwidgets/Delegates/Attendance/gmattendancedelegate.h \
    customwidgets/Delegates/Contacts/contactnamesearchdelegate.h \
    customwidgets/Delegates/Inventory/gminventorylistitemdelegate.h \
    customwidgets/Delegates/Inventory/gminventorytransactiondelegate.h \
    customwidgets/Delegates/Inventory/groupwisesalesreportdelegate.h \
    customwidgets/Delegates/Inventory/possalesitemsdelegate.h \
    customwidgets/Delegates/Ledgers/gmledgertransactiondelegate.h \
    customwidgets/Delegates/Notifications/notificationsdelegate.h \
    customwidgets/Delegates/Orders/gmitemwiseordersdelegate.h \
    customwidgets/Delegates/Orders/pendingdeliverydelegate.h \
    customwidgets/Delegates/Orders/salesorderstimebasedreportdelegate.h \
    customwidgets/Delegates/Payslip/gmpayslipdelegate.h \
    customwidgets/Delegates/Reconciliation/gmbankreconciliationdelegate.h \
    customwidgets/Delegates/Shift/gmshiftdelegate.h \
    customwidgets/Delegates/StockEntry/stockentrydelegate.h \
    customwidgets/Delegates/StockJournal/stockjournaldelegate.h \
    customwidgets/Delegates/StockRequest/stockrequestdelegate.h \
    customwidgets/Delegates/WorkOrder/kotreportdelegate.h \
    customwidgets/Delegates/WorkOrder/workorderdelegate.h \
    customwidgets/Delegates/billwisemappingdelegate.h \
    customwidgets/Delegates/closingstockretdelegate.h \
    customwidgets/Delegates/dailyclosingdelegate.h \
    customwidgets/Delegates/daybookreportdelegate.h \
    customwidgets/Delegates/itemchecklistdelegate.h \
    customwidgets/Delegates/itemmovementanalysisdelegate.h \
    customwidgets/Delegates/registerdelegate.h \
    customwidgets/Delegates/reportwithextracolumndelegate.h \
    customwidgets/Delegates/salesordersdelgate.h \
    customwidgets/Delegates/userpermissionsdelegate.h \
    customwidgets/Fifo/fifopopupdialog.h \
    customwidgets/Material/components/layouts/qtmaterialsnackbarlayout.h \
    customwidgets/Material/components/layouts/qtmaterialsnackbarlayout_p.h \
    customwidgets/Material/components/lib/qtmaterialcheckable.h \
    customwidgets/Material/components/lib/qtmaterialcheckable_internal.h \
    customwidgets/Material/components/lib/qtmaterialcheckable_p.h \
    customwidgets/Material/components/lib/qtmaterialoverlaywidget.h \
    customwidgets/Material/components/lib/qtmaterialripple.h \
    customwidgets/Material/components/lib/qtmaterialrippleoverlay.h \
    customwidgets/Material/components/lib/qtmaterialstatetransition.h \
    customwidgets/Material/components/lib/qtmaterialstatetransitionevent.h \
    customwidgets/Material/components/lib/qtmaterialstyle.h \
    customwidgets/Material/components/lib/qtmaterialstyle_p.h \
    customwidgets/Material/components/lib/qtmaterialtheme.h \
    customwidgets/Material/components/lib/qtmaterialtheme_p.h \
    customwidgets/Material/components/qtmaterialappbar.h \
    customwidgets/Material/components/qtmaterialappbar_p.h \
    customwidgets/Material/components/qtmaterialautocomplete.h \
    customwidgets/Material/components/qtmaterialautocomplete_internal.h \
    customwidgets/Material/components/qtmaterialautocomplete_p.h \
    customwidgets/Material/components/qtmaterialavatar.h \
    customwidgets/Material/components/qtmaterialavatar_p.h \
    customwidgets/Material/components/qtmaterialbadge.h \
    customwidgets/Material/components/qtmaterialbadge_p.h \
    customwidgets/Material/components/qtmaterialcheckbox.h \
    customwidgets/Material/components/qtmaterialcheckbox_p.h \
    customwidgets/Material/components/qtmaterialcircularprogress.h \
    customwidgets/Material/components/qtmaterialcircularprogress_internal.h \
    customwidgets/Material/components/qtmaterialcircularprogress_p.h \
    customwidgets/Material/components/qtmaterialdialog.h \
    customwidgets/Material/components/qtmaterialdialog_internal.h \
    customwidgets/Material/components/qtmaterialdialog_p.h \
    customwidgets/Material/components/qtmaterialdrawer.h \
    customwidgets/Material/components/qtmaterialdrawer_internal.h \
    customwidgets/Material/components/qtmaterialdrawer_p.h \
    customwidgets/Material/components/qtmaterialfab.h \
    customwidgets/Material/components/qtmaterialfab_p.h \
    customwidgets/Material/components/qtmaterialflatbutton.h \
    customwidgets/Material/components/qtmaterialflatbutton_internal.h \
    customwidgets/Material/components/qtmaterialflatbutton_p.h \
    customwidgets/Material/components/qtmaterialiconbutton.h \
    customwidgets/Material/components/qtmaterialiconbutton_p.h \
    customwidgets/Material/components/qtmateriallist.h \
    customwidgets/Material/components/qtmateriallist_p.h \
    customwidgets/Material/components/qtmateriallistitem.h \
    customwidgets/Material/components/qtmateriallistitem_p.h \
    customwidgets/Material/components/qtmaterialmenu.h \
    customwidgets/Material/components/qtmaterialmenu_internal.h \
    customwidgets/Material/components/qtmaterialmenu_p.h \
    customwidgets/Material/components/qtmaterialpaper.h \
    customwidgets/Material/components/qtmaterialpaper_p.h \
    customwidgets/Material/components/qtmaterialprogress.h \
    customwidgets/Material/components/qtmaterialprogress_internal.h \
    customwidgets/Material/components/qtmaterialprogress_p.h \
    customwidgets/Material/components/qtmaterialradiobutton.h \
    customwidgets/Material/components/qtmaterialradiobutton_p.h \
    customwidgets/Material/components/qtmaterialraisedbutton.h \
    customwidgets/Material/components/qtmaterialraisedbutton_p.h \
    customwidgets/Material/components/qtmaterialscrollbar.h \
    customwidgets/Material/components/qtmaterialscrollbar_internal.h \
    customwidgets/Material/components/qtmaterialscrollbar_p.h \
    customwidgets/Material/components/qtmaterialslider.h \
    customwidgets/Material/components/qtmaterialslider_internal.h \
    customwidgets/Material/components/qtmaterialslider_p.h \
    customwidgets/Material/components/qtmaterialsnackbar.h \
    customwidgets/Material/components/qtmaterialsnackbar_internal.h \
    customwidgets/Material/components/qtmaterialsnackbar_p.h \
    customwidgets/Material/components/qtmaterialtable.h \
    customwidgets/Material/components/qtmaterialtable_p.h \
    customwidgets/Material/components/qtmaterialtabs.h \
    customwidgets/Material/components/qtmaterialtabs_internal.h \
    customwidgets/Material/components/qtmaterialtabs_p.h \
    customwidgets/Material/components/qtmaterialtextfield.h \
    customwidgets/Material/components/qtmaterialtextfield_internal.h \
    customwidgets/Material/components/qtmaterialtextfield_p.h \
    customwidgets/Material/components/qtmaterialtoggle.h \
    customwidgets/Material/components/qtmaterialtoggle_internal.h \
    customwidgets/Material/components/qtmaterialtoggle_p.h \
    customwidgets/Misc/customshadoweffect.h \
    customwidgets/Misc/getschedule.h \
    customwidgets/Misc/gmcpbar.h \
    customwidgets/Misc/hashtagedit.h \
    customwidgets/Misc/hashtaglinewidget.h \
    customwidgets/Misc/loading.h \
    customwidgets/Misc/sidebarbutton.h \
    customwidgets/Models/gmaccesscontrolmodel.h \
    customwidgets/Models/gmbillwisemappingmodel.h \
    customwidgets/Models/gmemployeemodel.h \
    customwidgets/Models/gmfifomodel.h \
    customwidgets/Models/gmgodownallocationmodel.h \
    customwidgets/Models/gmgodowntransfermodel.h \
    customwidgets/Models/gminventoryitemmodel.h \
    customwidgets/Models/gmitemchecklistmodel.h \
    customwidgets/Models/gmitemwiseordermodel.h \
    customwidgets/Models/gmjournalentrymodel.h \
    customwidgets/Models/gmledgeritemmodel.h \
    customwidgets/Models/gmnotificationlistmodel.h \
    customwidgets/Models/gmpaymententrymodel.h \
    customwidgets/Models/gmpayslipmodel.h \
    customwidgets/Models/gmreceiptentrymodel.h \
    customwidgets/Models/gmreconciliationmodel.h \
    customwidgets/Models/gmshiftmodel.h \
    customwidgets/Models/gmshiftsalesmodel.h \
    customwidgets/Models/gmsqlquerymodel.h \
    customwidgets/Models/gmstockentrymodel.h \
    customwidgets/Models/gmstockinentrymodel.h \
    customwidgets/Models/gmstockjournalmodel.h \
    customwidgets/Models/gmstockrequestmodel.h \
    customwidgets/Models/gmwastageentrymodel.h \
    customwidgets/Models/gmworkordermodel.h \
    customwidgets/Models/possalesitemsmodel.h \
    customwidgets/SearchWidgets/AccountGroup/gmaccountgroupsearchwidget.h \
    customwidgets/SearchWidgets/Contact/gmcontactlinematerial.h \
    customwidgets/SearchWidgets/Employee/employeesearchdelegate.h \
    customwidgets/SearchWidgets/Employee/gmemployeelinematerial.h \
    customwidgets/SearchWidgets/Employee/gmemployeesearchline.h \
    customwidgets/SearchWidgets/Employee/gmemployeesearchlistwidgetlite.h \
    customwidgets/SearchWidgets/Employee/gmemployeesearchlite.h \
    customwidgets/SearchWidgets/Employee/gmemployeesearchproxymodel.h \
    customwidgets/SearchWidgets/Employee/gmemployeesearchwidget.h \
    customwidgets/SearchWidgets/Godown/gmgodownlinematerial.h \
    customwidgets/SearchWidgets/Godown/gmgodownsearchlistwidgetlite.h \
    customwidgets/SearchWidgets/Godown/gmgodownsearchlite.h \
    customwidgets/SearchWidgets/Godown/gmgodownsearchproxymodel.h \
    customwidgets/SearchWidgets/Godown/godownsearchdelegate.h \
    customwidgets/SearchWidgets/InventoryGroup/gminventorygroupsearchwidget.h \
    customwidgets/SearchWidgets/Inventoryitem/Completer/gminventoryitemsearch.h \
#    customwidgets/SearchWidgets/Inventoryitem/gminventoryitemlinematerial.h \
    customwidgets/SearchWidgets/Ledger/gmledgerlinematerial.h \
    customwidgets/SearchWidgets/Ledger/gmledgerlinewidget.h \
    customwidgets/SearchWidgets/Pricelist/gmpricelistlinematerial.h \
    customwidgets/SearchWidgets/Uom/uomsearchwidget.h \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchlistwidgetlite.h \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchlite.h \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchproxymodel.h \
    customwidgets/SearchWidgets/Widgets/widgetsearchdelegate.h \
    customwidgets/TableViews/employeetableview.h \
    customwidgets/TableViews/inventoryvouchertableview.h \
    customwidgets/TableViews/itemwiseentrytableview.h \
    customwidgets/TableViews/ledgervouchertableview.h \
    customwidgets/TableViews/ledgerwisetableview.h \
    customwidgets/TableViews/paysliptableview.h \
    customwidgets/TableViews/reportstableview.h \
    customwidgets/TableViews/shiftsalestableview.h \
    customwidgets/TableViews/stockentrytableview.h \
    customwidgets/TableViews/userpermissionstableview.h \
    customwidgets/appbarwidget.h \
    customwidgets/barcodeprintwidget.h \
    customwidgets/checklistpromptdialog.h \
    customwidgets/filterwidget.h \
    customwidgets/gmreportsortfilterproxymodel.h \
    customwidgets/godownselectorwidget.h \
    customwidgets/itemchecklistwidget.h \
    customwidgets/modeofservicebutton.h \
    customwidgets/showvoucherswidget.h \
    customwidgets/test/flowlayout.h \
    dashboard/accountsmaindashboard.h \
    dashboard/customerdashboard.h \
    dashboard/inventoryitemdashboard.h \
    dashboard/purchasesmaindash.h \
    dashboard/receiptsmaindash.h \
    dashboard/salesmaindash.h \
    database/Counter/TableManagement/tablereservationdatabasehelper.h \
    database/Counter/TableManagement/tablesmasterhelper.h \
    database/Reports/closingstockhelper.h \
    database/Reports/ledgerhelpermt.h \
    database/Settings/ConfigurationSettingsDatabaseHelper.h \
    database/Settings/configsettingsvariables.h \
        database/Settings/configsettingsvalues.h \
    database/Settings/uisettingsdatabasehelper.h \
    database/Settings/uisettingsvariables.h \
    database/databasehelper/bulkloaddatabasehelper.h \
    database/databasehelper/databaseupdater.h \
    database/finance/Closing/restaurantshiftdatabasehelper.h \
    database/finance/ItemTransaction/transactionfifodatabasehelper.h \
    database/finance/proforma/proformadatabasehelper.h \
    database/finance/salesvoucher/salesvoucherdeleteddatabasehelper.h \
    database/hr/attendancedatabasehelper.h \
    database/hr/payslipdatabasehelper.h \
    database/inventory/StockRequest/stockrequestdatabasehelper.h \
    database/inventory/category/categorydatabasehelper.h \
    database/inventory/defective/defectivedatabasehelper.h \
    database/inventory/godowntransfer/godowntransferdatabasehelper.h \
    database/inventory/inventorytemplate/inventorytemplatedatabasehelper.h \
    database/inventory/label/itemlabeldatabasehelper.h \
    database/inventory/receiptnote/receiptnotedatabasehelper.h \
    database/Notifications/receivechanneldatabasehelper.h \
    database/Notifications/sendchanneldatabasehelper.h \
    database/inventory/sales_inventory_items/bundledatabasehelper.h \
    database/inventory/salesorder/itemwisesalesorderdatabasehelper.h \
    database/inventory/workorder/workorderdatabasehelper.h \
    database/projects/hashtagdatabasehelper.h \
    database/voucherdbabstract.h \
    datamodels/Counter/denominationsdatamodel.h \
    datamodels/Counter/shiftledgersdatamodel.h \
    datamodels/Counter/tablemasterdatamodel.h \
    datamodels/Counter/tablereservationdatamodel.h \
    datamodels/Settings/licenseinfodatamodel.h \
    datamodels/Settings/uisettingsdatamodel.h \
    datamodels/godowns/godowntransactiondatamodel.h \
    datamodels/hr/attendancedatamodel.h \
    datamodels/hr/attendancelistdatamodel.h \
    datamodels/hr/employeesalarydatamodel.h \
    datamodels/hr/payslipdatamodel.h \
    datamodels/hr/uiaccesscontroldatamodel.h \
    datamodels/inventory/Label/itemlabeldatamodel.h \
    datamodels/inventory/category/categorydatamodel.h \
    datamodels/inventory/sales_inventory_item/inventoryitembatchmodel.h \
    datamodels/inventory/sales_inventory_item/skudatamodel.h \
    datamodels/sampleobjectdatamodel.h \
    datamodels/transaction/GMTaxDataModel.h \
    datamodels/transaction/gmtaxclass.h \
    datamodels/transaction/gmvouchertypes.h \
    datamodels/transaction/itemfifodatamodel.h \
    datamodels/transaction/requirementvoucherdataobject.h \
    datamodels/utils/emailmodel.h \
    ecommerce/cartwidget.h \
    ecommerce/itemdetailwidget.h \
    ecommerce/itemselectorwidget.h \
    ecommerce/shippingdetailseditor.h \
    finance/reports/BankReconciliation/bankreconciliation.h \
    finance/reports/GSTReport/gstreport.h \
    finance/reports/GSTReport/hsnreportdelegate.h \
    finance/reports/GSTReport/vatreport.h \
    finance/reports/SalesOrders/deliveryordersmodel.h \
    finance/reports/SalesOrders/pendingorders.h \
    finance/reports/SalesOrders/pendingordersdelegate.h \
    finance/transactions/BillwiseRecords/billwisemappingeditor.h \
    finance/transactions/LedgerView/ledgerwisevouchertableview.h \
    finance/transactions/LedgerView/ledgerwisevoucherview.h \
    finance/transactions/Proforma/proformainvoiceeditor.h \
    finance/transactions/calculator/fifocalculator.h \
    finance/transactions/contra/contravouchereditor.h \
    finance/transactions/creditnote/creditnotevouchereditor.h \
    finance/transactions/debitnote/debitnotevouchereditor.h \
    finance/transactions/journals/journalvouchereditor.h \
    finance/transactions/payments/paymentvouchereditor.h \
    finance/transactions/purchases/purchasevouchereditor.h \
    finance/transactions/receipts/receiptvouchereditor.h \
    finance/transactions/sales/salesadjustmentwidget.h \
    finance/transactions/sales/salesvouchereditor.h \
    datamodels/Notification/notificationdatamodel.h \
    finance/transactions/sales/voucherrecalculater.h \
    hr/Reports/payslipreport.h \
    hr/addemployeesalarydetails.h \
    hr/attendanceeditor.h \
    hr/payslipgenerationeditor.h \
    hr/uacsortmodel.h \
    hr/usergrouppermissionseditor.h \
    inventory/masters/item_label_data/itemlabeldata.h \
    inventory/masters/sales_inventory_items/bundle/itembundlelistdelegate.h \
    inventory/masters/sales_inventory_items/bundle/itembundlelistmodel.h \
    inventory/masters/sales_inventory_items/bundle/itembundletableview.h \
    inventory/masters/sales_inventory_items/updateplulisttextfileclass.h \
    inventory/pricelist/pricelistbyitem.h \
    inventory/pricelist/pricelistdelegate.h \
    inventory/pricelist/pricelistmodel.h \
    inventory/pricelist/pricelistsortmodel.h \
    inventory/pricelist/pricelisttableview.h \
    inventory/reports/CreditNoteReport/creditnotereport.h \
    inventory/reports/DailyCosting/dailycostingreport.h \
    inventory/reports/DebitNoteReport/debitnotereport.h \
    inventory/reports/ItemwiseReport/itemwisesalesorderbymode.h \
    inventory/reports/MovementAnalysis/godownwiseitemmovement.h \
    inventory/reports/MovementAnalysis/groupwiseitemmovement.h \
    inventory/reports/MovementAnalysis/ledgerwiseitemmovement.h \
    inventory/reports/PurchaseReport/purchasereport.h \
    inventory/reports/WastageReport/wastagereport.h \
    inventory/reports/WorkOrderReport/kotreport.h \
    inventory/reports/WorkOrderReport/workorderreport.h \
    inventory/transactions/Defective/wastageentryeditor.h \
    inventory/transactions/InventoryTemplate/inventorytemplateeditor.h \
    inventory/transactions/InventoryTemplate/inventorytemplatelist.h \
    inventory/transactions/ItemwiseSalesOrder/additemwisesalesorder.h \
    inventory/transactions/ItemwiseSalesOrder/iteemwisesalesorderlist.h \
    inventory/transactions/ItemwiseSalesOrder/itemwisesodatewisereport.h \
    inventory/transactions/StockRequest/stockrequesteditor.h \
    inventory/transactions/deliverynote/deliverynoteeditor.h \
    inventory/transactions/materialinout/materialinouteditor.h \
    inventory/transactions/purchaseorders/purchaseordervouchereditor.h \
    inventory/transactions/receiptnotes/receiptnotevouchereditor.h \
    inventory/transactions/salesorders/salesordervouchereditor.h \
    inventory/transactions/stockentry/stockentryeditor.h \
    inventory/transactions/stockjournal/stockjournaleditor.h \
        mainwindow.h \
    database/databasehelper/databasehelper.h \
    database/inventory/sales_inventory_groups/salesinventorygroupsdatabasehelper.h \
    database/inventory/sales_inventory_items/salesinventoryitemdatabasehelper.h \
    datamodels/inventory/sales_inventory_item/inventoryitemdatamodel.h \
    datamodels/inventory/sales_inventory_group/inventoryitemgroupdatamodel.h \
    datamodels/accounts/ledgermasterdatamodel.h \
    datamodels/accounts/accountgroupdatamodel.h \
    datamodels/inventory/property/propertydatamodel.h \
    datamodels/inventory/sales_inventory_item/compounditemdataobject.h \
    datamodels/inventory/uom/uomdatamodel.h \
    datamodels/inventory/pricelist/pricelistdataobject.h \
    datamodels/transaction/salestransactiondatamodel.h \
    datamodels/transaction/generalvoucherdataobject.h \
    database/databasehelper/databasevalues.h \
    database/finance/ledgermaster/ledgermasterdatabasehelper.h \
    database/finance/accountmaster/accountgroupmasterdatabasehelper.h \
    database/finance/salesvoucher/salesvoucherdatabasehelper.h \
    database/finance/purchasevoucher/purchasevoucherdatabasehelper.h \
    database/finance/receiptvoucher/receiptvoucherdatabasehelper.h \
    database/finance/paymentvoucher/paymentvoucherdatabasehelper.h \
    database/finance/creditnote/creditnotevoucherdatabasehelper.h \
    database/finance/debitnote/debitnotevoucherdatabasehelper.h \
    database/finance/contra/contravoucherdatabasehelper.h \
    database/inventory/pricelist/pricelistdatabasehelper.h \
    database/inventory/uom/uomdatabasehelper.h \
    database/inventory/salesorder/salesorderdatabasehelper.h \
    database/inventory/purchaseorder/purchaseorderdatabasehelper.h \
    database/inventory/deliverynote/deliverynotedatabasehelper.h \
    database/inventory/quotation/quotationdatabasehelper.h \
    database/inventory/property/propertydatabasehelper.h \
    database/inventory/materialinout/materialinoutdatabasehelper.h \
    database/inventory/stockentry/stockentrydatabasehelper.h \
    database/inventory/stockjournal/stockjournaldatabasehelper.h \
    datamodels/inventory/godown/godowndataobject.h \
    database/inventory/godown/godowndatabasehelper.h \
    datamodels/accounts/transactionreferenceobject.h \
    datamodels/accounts/chequedetail.h \
    datamodels/accounts/ledgerdetaildatamodel.h \
    customwidgets/section.h \
    customwidgets/gmcombobox.h \
    customwidgets/gmsearchlineedit.h \
    folder/lineediticon.h\
    datamodels/projects/projectsdataobject.h \
    datamodels/projects/projecttaskdataobject.h \
    datamodels/users/userprofiledataobject.h \
    customwidgets/sharebutton.h \
    projects/WorkOrder/workordereditor.h \
    projects/WorkOrder/workordergenerator.h \
    projects/WorkOrder/workorderlist.h \
    projects/quotations/quotaitonslist.h \
    projects/quotations/quotationeditor.h \
    sharetools/email/emailthread.h \
    sharetools/email/emailwidget.h \
    sharetools/pdf/pdfhelper.h \
    sharetools/print/printdotmatrix.h \
    sharetools/print/printoptions.h \
    sharetools/print/voucherprinter.h \
    sharetools/sharetools.h \
    sharetools/email/email.h \
    sharetools/excel/excel.h \
    customwidgets/defaultdashboard.h \
    projects/projects.h \
    projects/requirements/requirementslist.h \
    customwidgets/lineedittest.h \
    datamodels/addressbook/addressbookdatamodel.h \
    database/addressBook/addressbookdatabasehelper.h \
    finance/masters/accountgroups/addaccountgroup.h \
    inventory/masters/uom/addconversion.h \
    inventory/masters/uom/adduom.h \
    sharetools/sms/smswidget.h \
    utils/AppUpdater/Downloader.h \
    utils/AppUpdater/QSimpleUpdater.h \
    utils/AppUpdater/Updater.h \
    utils/AppUpdater/appupdater.h \
    utils/DatabaseUpdater/configdbupdater.h \
    utils/DatabaseUpdater/databaseupdaterwidget.h \
    utils/DatabaseUpdater/dbbackuphelper.h \
    utils/License/licensechecker.h \
    utils/QRCodeGenerator/qrcode.h \
    utils/SettingsHelper/settingshelper.h \
    utils/editorstatus.h \
    utils/duplicateitemsdialog.h \
    utils/gmfileuploadhelper.h \
    utils/itemsynctool.h \
    utils/logger.h \
    utils/logincontroller.h \
    voucherOperations/VocuherList/templatelist.h \
    voucherOperations/VoucherEditor/vouchereditor.h \
    voucherOperations/coupledvoucherhandler.h \
    voucherOperations/vouchereditorselector.h \
    warehouse/godowntransfer/godowntransfereditor.h \
    warehouse/godowntransfer/godowntransfer.h \
    addressbook/addressbook.h \
    addressbook/adressbook_display.h \
    finance/masters/ledgers/addledger.h \
    inventory/masters/godowns/addgodown.h \
    inventory/masters/properties/addproperty.h \
    inventory/masters/properties/propertylist.h \
    inventory/masters/sales_inventory_groups/additemgroups.h \
    inventory/masters/sales_inventory_items/additemprice.h \
    inventory/masters/sales_inventory_items/additems.h \
    inventory/pricelist/addpricelist.h \
    projects/quotations/addquotation.h \
    projects/quotations/quotations.h \
    projects/requirements/additemadditionalrequirement.h \
    projects/requirements/additemrequirement.h \
    projects/requirements/requirement.h \
    projects/addproject.h \
    projects/projectwidget.h \
    addressbook/contacts_sidebar.h \
    dashboard/dashboard_sidebar.h \
    helpdesk/helpdesk_sidebar.h \
    projects/projects_sidebar.h \
    services/services_sidebar.h \
    toolbar/maintoolbar.h \
    toolbar/utilities_toolbar.h \
    inventory/masters/brands/addbrands.h \
    datamodels/inventory/brands/brandsdatamodel.h \
    database/inventory/brands/brandsdatabasehelper.h \
    database/projects/requirementsdatabasehelper.h \
    datamodels/addressbook/employeeaddressdatamodel.h \
    customwidgets/customitemview.h \
    customwidgets/ledgercompletertablemodel.h \
    customwidgets/listviewdelegate.h \
    sharetools/print/printerhelper.h \
    database/projects/projectsdatabasehelper.h \
    customwidgets/gmitemsearch.h \
    customwidgets/searchlistitemwidget.h \
    customwidgets/gmlistwidget.h \
    customwidgets/gmitemsearchwidget.h \
    customwidgets/gmsearchledgerwidgetitem.h \
    customwidgets/gmledgersearch.h \
    customwidgets/gmledgersearchwidget.h \
    projects/quotations/quotationdetails.h \
    database/finance/journalvoucher/journalvoucherdatabasehelper.h \
    hr/adduserprofile.h \
    finance/masters/termsconditions/termsconditions.h \
    database/finance/terms/termsdatabasehelper.h \
    finance/reports/LedgerReport/ledgerreport.h \
    database/hr/usergroupdatabasehelper.h \
    database/hr/userprofiledatabasehelper.h \
    datamodels/hr/usergroupdatamodel.h \
    datamodels/hr/userprofiledatamodel.h \
    customwidgets/form.h \
    customwidgets/importvoucherlist.h \
    database/inventory/sales_inventory_items/inventoryitemimagesdatabasehelper.h \
    datamodels/inventory/sales_inventory_item/itemimagedatamodel.h \
    datamodels/addressbook/addressbooksmall.h \
    login/loginpage.h \
    login/loginvalues.h \
    customwidgets/ContactSearch/gmcontactsearchwidget.h \
    customwidgets/ContactSearch/contactlistwidgetitem.h \
    customwidgets/ContactSearch/gmcontactsearch.h \
    database/projects/oldquote/oldquotationdatabasehelper.h \
    projects/Draftsman/draftsmanview.h \
    projects/Draftsman/quoteview.h \
    projects/Draftsman/itemdetailview.h \
    datamodels/projects/Documents/documentsdatamodel.h \
    datamodels/Documents/documentdatamodel.h \
    projects/History/previousquotationslist.h \
    projects/History/previousquotationwidget.h \
    datamodels/projects/Quotation/quotationstatus.h \
    projects/Documents/documentslist.h \
    projects/WorkOrder/workorderitemdetail.h \
    projects/WorkOrder/workorderquotes.h \
    projects/PendingApprovals/pendingapprovalslist.h \
    counter/MainScreen/denominations.h \
    counter/Shift/shiftentry.h \
    counter/Reports/billwisereport.h \
    counter/Reports/reportsmainwindow.h \
    counter/Shift/closingentry.h \
    counter/MainScreen/addressdialog.h \
    counter/Reports/timebasedsales.h \
    counter/MainScreen/restuarantcountermainwindow.h \
    finance/reports/TrialBalance/trialbalance.h \
    finance/reports/ProfitAndLossReport/profitandlossreport.h \
    finance/reports/BalanceSheet/balancesheet.h \
    datamodels/projects/Quotation/documenttype.h \
    customwidgets/Bank/chequewidget.h \
    database/finance/reports/reportsdatabasehelper.h \
    purchases/reports/ItemsReserved/itemsreserved.h \
    purchases/reports/CostEstimates/costestimates.h \
    customwidgets/numberpad.h \
    counter/MainScreen/modeofpay.h \
    counter/MainScreen/itemdetail.h \
    database/Reports/ledgerhelper.h \
    database/Reports/inventoryhelper.h \
    inventory/reports/GroupwiseReport/groupwisereport.h \
    datamodels/Counter/servicemode.h \
    counter/PrinterHelper/counterprinterhelper.h \
    counter/Reports/todaysbills.h \
    customwidgets/Validator/myvalidator.h \
    counter/Settings/settings.h \
    counter/Settings/about.h \
    counter/Settings/helpcontents.h \
    datamodels/Counter/shiftdatamodel.h \
    database/finance/Closing/shiftdatabasehelper.h \
    addressbook/companyprofilewidget.h \
    database/addressBook/companyprofiledatabasehelper.h \
    datamodels/addressbook/companyprofiledatamodel.h \
    counter/MainScreen/assignsalesman.h \
    customwidgets/qtbutton.h \
    datamodels/Counter/countersettingsdatamodel.h \
    database/Counter/countersettingsdatabasehelper.h \
    services/Transactions/serviceregistrationwidget.h \
    services/Transactions/serviceregisterlist.h \
    database/Service/seviceregisterdatabasehelper.h \
    datamodels/Services/servicecomplaintregisterdatamodel.h \
    datamodels/Services/servicestatus.h \
    datamodels/Services/complaintlogdatamodel.h \
    datamodels/inventory/salesinventoryitemstablemodel.h \
    counter/MainScreen/restaurantextras.h \
    counter/MainScreen/passwordentry.h \
    counter/MainScreen/tableselect.h \
    counter/MainScreen/salesitems.h \
    counter/MainScreen/salesgroups.h \
    database/finance/ItemTransaction/itemtransactiondatabasehelper.h \
    datamodels/transaction/itemtransactiondatamodel.h \
    datamodels/Services/servicecomplaintdescriptionmodel.h \
    counter/Reports/shiftwisereport.h \
    counter/Reports/dailyclosingsalesreport.h \
    counter/Reports/waiterwisesalesreport.h \
    counter/Reports/modeofservicewisereport.h \
    counter/Reports/complimentarysalesreport.h \
    counter/Reports/discountsreport.h \
    database/finance/TransactionHelper/transactionhelper.h \
    customwidgets/mydelegate.h \
    customwidgets/test/testform.h \
    customwidgets/test/gmitemsortfilterproxymodel.h \
    customwidgets/test/ledgerreportdelegate.h \
    database/Counter/billofmaterialsingredientsdatabasehelper.h \
    datamodels/Counter/restaurantingredientsdatamodel.h \
    counter/MainScreen/miscellaneousitems.h \
    customwidgets/Delegates/itemwisesalesdelegate.h \
    customwidgets/Delegates/reportcommondelegate.h \
    sharetools/email/SMTP/gmail/smtp.h \
    counter/Reports/Restaurant/restaurantsalesordersreport.h \
    counter/Reports/Restaurant/restaurantdeliveryreport.h \
    counter/Reports/Restaurant/restaurantpendingdelivery.h \
    counter/Reports/Restaurant/restaurantsaveddrafts.h \
    counter/Reports/Restaurant/zomatoreport.h \
    customwidgets/test/itemcompleter.h \
    database/Reports/vatreportdatabasehelper.h \
    counter/Settings/kotprintersettings.h \
    customwidgets/Delegates/trialbalancedelegate.h \
    customwidgets/Crypto/simplecrypt.h \
    counter/Reports/Restaurant/restaurantclosingstock.h \
    database/finance/Closing/dailyclosingdatabasehelper.h \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchlite.h \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchlistwidgetlite.h \
    customwidgets/SearchWidgets/Inventoryitem/itemsearchdelegate.h \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchproxymodel.h \
    counter/MainScreen/restaurantitemdetail.h \
    inventory/masters/sales_inventory_items/salesinventoryopening.h \
    finance/masters/ledgers/ledgeropeningvalues.h \
    customwidgets/Delegates/todaysbillsdelegate.h \
    sharetools/excel/excelreporthelper.h \
    customwidgets/Delegates/billwisereportdelegate.h \
    datamodels/inventory/uom/uomconversiondatamodel.h \
    customwidgets/Delegates/salesmarginreportdelegate.h \
    database/finance/BillwiseRecords/billwiserecordsdatabasehelper.h \
    datamodels/transaction/billwiserecorddatamodel.h \
    finance/transactions/BillwiseRecords/addbillwiserecord.h \
    database/finance/banking/chequedetailsdatabasehelper.h \
    customwidgets/SearchWidgets/Ledger/gmledgersearchlite.h \
    customwidgets/SearchWidgets/Ledger/gmledgersearchlistwidgetlite.h \
    customwidgets/SearchWidgets/Ledger/gmledgersearchproxymodel.h \
    customwidgets/SearchWidgets/Ledger/gmledgersearchdelegate.h \
    finance/transactions/calculator/transactioncalculator.h \
    customwidgets/LedgersView/ledgersdisplaycontroller.h \
    customwidgets/LedgersView/gmtablewidgetledger.h \
    customwidgets/Notifications/qnotify.h \
    database/finance/TransactionHelper/generalvoucherdatabasehelper.h \
    database/Reports/accountingreportdatabasehelper.h \
    webservices/test/webservicetestsms.h


FORMS += \
    CommonUi/uimain.ui \
    Notifications/notificationledgerslist.ui \
    counter/MainScreen/customerscreen.ui \
    counter/MainScreen/godownallocationwidget.ui \
    counter/MainScreen/itempricedetailswidget.ui \
    counter/MainScreen/modeofpaystore.ui \
    counter/MainScreen/modeofservicewidget.ui \
    counter/MainScreen/paymentsplitwidget.ui \
    counter/MainScreen/selectitemswidget.ui \
    counter/MainScreen/shiftentrywidget.ui \
    counter/MainScreen/shiftvalueseditor.ui \
    counter/Reports/Restaurant/itemtrasactionlist.ui \
    counter/Shift/restaurantshiftentry.ui \
    customwidgets/Basic/gmcardwidget.ui \
    customwidgets/Company/companyselectorwidget.ui \
    customwidgets/Fifo/fifopopupdialog.ui \
    customwidgets/Misc/getschedule.ui \
    customwidgets/Misc/hashtaglinewidget.ui \
    customwidgets/SearchWidgets/Employee/gmemployeesearchlistwidgetlite.ui \
    customwidgets/SearchWidgets/Godown/gmgodownsearchlistwidgetlite.ui \
    customwidgets/SearchWidgets/Widgets/gmwidgetsearchlistwidgetlite.ui \
    customwidgets/barcodeprintwidget.ui \
    customwidgets/checklistpromptdialog.ui \
    customwidgets/godownselectorwidget.ui \
    customwidgets/itemchecklistwidget.ui \
    customwidgets/showvoucherswidget.ui \
    customwidgets/test/clstestwid.ui \
    dashboard/accountsmaindashboard.ui \
    dashboard/customerdashboard.ui \
    dashboard/inventoryitemdashboard.ui \
    dashboard/purchasesmaindash.ui \
    dashboard/receiptsmaindash.ui \
    dashboard/salesmaindash.ui \
    ecommerce/cartwidget.ui \
    ecommerce/itemdetailwidget.ui \
    ecommerce/itemselectorwidget.ui \
    ecommerce/shippingdetailseditor.ui \
    finance/reports/BankReconciliation/bankreconciliation.ui \
    finance/reports/GSTReport/gstreport.ui \
    finance/reports/GSTReport/vatreport.ui \
    finance/reports/SalesOrders/pendingorders.ui \
    finance/transactions/LedgerView/ledgerwisevouchertableview.ui \
    finance/transactions/Proforma/proformainvoiceeditor.ui \
    finance/transactions/sales/salesadjustmentwidget.ui \
    hr/Reports/payslipreport.ui \
    hr/addemployeesalarydetails.ui \
    hr/attendanceeditor.ui \
    hr/payslipgenerationeditor.ui \
    inventory/masters/item_label_data/itemlabeldata.ui \
    inventory/reports/CreditNoteReport/creditnotereport.ui \
    inventory/reports/DailyCosting/dailycostingreport.ui \
    inventory/reports/DebitNoteReport/debitnotereport.ui \
    inventory/reports/ItemwiseReport/itemwisesalesorderbymode.ui \
    inventory/reports/MovementAnalysis/godownwiseitemmovement.ui \
    inventory/reports/MovementAnalysis/groupwiseitemmovement.ui \
    inventory/reports/MovementAnalysis/ledgerwiseitemmovement.ui \
    inventory/reports/PurchaseReport/purchasereport.ui \
    inventory/reports/WastageReport/wastagereport.ui \
    inventory/reports/WorkOrderReport/workorderreport.ui \
    inventory/transactions/InventoryTemplate/inventorytemplateeditor.ui \
    inventory/transactions/InventoryTemplate/inventorytemplatelist.ui \
    inventory/transactions/ItemwiseSalesOrder/additemwisesalesorder.ui \
    inventory/transactions/ItemwiseSalesOrder/iteemwisesalesorderlist.ui \
    inventory/transactions/ItemwiseSalesOrder/itemwisesodatewisereport.ui \
    inventory/transactions/materialinout/materialinouteditor.ui \
        mainwindow.ui \
    projects/WorkOrder/workordereditor.ui \
    projects/WorkOrder/workorderlist.ui \
    projects/quotations/quotaitonslist.ui \
    projects/quotations/quotationeditor.ui \
    sharetools/email/emailwidget.ui \
    sharetools/print/printoptions.ui \
    sharetools/sharetools.ui \
    sharetools/email/email.ui \
    sharetools/excel/excel.ui \
    customwidgets/defaultdashboard.ui \
    projects/projects.ui \
    projects/requirements/requirementslist.ui \
    customwidgets/lineedittest.ui \
    finance/masters/accountgroups/addaccountgroup.ui \
    inventory/masters/uom/addconversion.ui \
    inventory/masters/uom/adduom.ui \
    sharetools/sms/smswidget.ui \
    utils/AppUpdater/Downloader.ui \
    utils/DatabaseUpdater/databaseupdaterwidget.ui \
    utils/duplicateitemsdialog.ui \
    utils/itemsynctool.ui \
    voucherOperations/VocuherList/templatelist.ui \
    warehouse/godowntransfer/godowntransfereditor.ui \
    warehouse/godowntransfer/godowntransfer.ui \
    warehouse/godowntransfer/addgodowntransfer.ui \
    addressbook/addressbook.ui \
    addressbook/adressbook_display.ui \
    finance/masters/ledgers/addledger.ui \
    inventory/masters/godowns/addgodown.ui \
    inventory/masters/properties/addproperty.ui \
    inventory/masters/properties/propertylist.ui \
    inventory/masters/sales_inventory_groups/additemgroups.ui \
    inventory/masters/sales_inventory_items/additemprice.ui \
    inventory/masters/sales_inventory_items/additems.ui \
    inventory/pricelist/addpricelist.ui \
    projects/quotations/addquotation.ui \
    projects/quotations/quotations.ui \
    projects/requirements/additemadditionalrequirement.ui \
    projects/requirements/additemrequirement.ui \
    projects/requirements/requirement.ui \
    projects/addproject.ui \
    projects/projectwidget.ui \
    addressbook/contacts_sidebar.ui \
    dashboard/dashboard_sidebar.ui \
    helpdesk/helpdesk_sidebar.ui \
    projects/projects_sidebar.ui \
    services/services_sidebar.ui \
    toolbar/maintoolbar.ui \
    toolbar/utilities_toolbar.ui \
    inventory/masters/brands/addbrands.ui \
    customwidgets/searchlistitemwidget.ui \
    customwidgets/gmitemsearchwidget.ui \
    customwidgets/gmsearchledgerwidgetitem.ui \
    customwidgets/gmledgersearchwidget.ui \
    projects/quotations/quotationdetails.ui \
    hr/adduserprofile.ui \
    finance/masters/termsconditions/termsconditions.ui \
    finance/reports/LedgerReport/ledgerreport.ui \
    customwidgets/form.ui \
    customwidgets/importvoucherlist.ui \
    login/loginpage.ui \
    customwidgets/ContactSearch/gmcontactsearchwidget.ui \
    customwidgets/ContactSearch/contactlistwidgetitem.ui \
    projects/Draftsman/draftsmanview.ui \
    projects/Draftsman/quoteview.ui \
    projects/Draftsman/itemdetailview.ui \
    projects/History/previousquotationslist.ui \
    projects/History/previousquotationwidget.ui \
    projects/Documents/documentslist.ui \
    projects/WorkOrder/workorderitemdetail.ui \
    projects/WorkOrder/workorderquotes.ui \
    projects/PendingApprovals/pendingapprovalslist.ui \
    counter/MainScreen/denominations.ui \
    counter/Shift/shiftentry.ui \
    counter/Reports/billwisereport.ui \
    counter/Reports/reportsmainwindow.ui \
    counter/Shift/closingentry.ui \
    counter/MainScreen/addressdialog.ui \
    counter/Reports/timebasedsales.ui \
    counter/MainScreen/restuarantcountermainwindow.ui \
    finance/reports/TrialBalance/trialbalance.ui \
    finance/reports/ProfitAndLossReport/profitandlossreport.ui \
    finance/reports/BalanceSheet/balancesheet.ui \
    purchases/reports/ItemsReserved/itemsreserved.ui \
    purchases/reports/CostEstimates/costestimates.ui \
    customwidgets/numberpad.ui \
    counter/MainScreen/modeofpay.ui \
    counter/MainScreen/itemdetail.ui \
    inventory/reports/GroupwiseReport/groupwisereport.ui \
    counter/Reports/todaysbills.ui \
    counter/Settings/settings.ui \
    counter/Settings/about.ui \
    counter/Settings/helpcontents.ui \
    addressbook/companyprofilewidget.ui \
    counter/MainScreen/assignsalesman.ui \
    services/Transactions/serviceregistrationwidget.ui \
    services/Transactions/serviceregisterlist.ui \
    counter/MainScreen/restaurantextras.ui \
    counter/MainScreen/passwordentry.ui \
    counter/MainScreen/tableselect.ui \
    counter/MainScreen/salesitems.ui \
    counter/MainScreen/salesgroups.ui \
    counter/Reports/shiftwisereport.ui \
    counter/Reports/dailyclosingsalesreport.ui \
    counter/Reports/waiterwisesalesreport.ui \
    counter/Reports/modeofservicewisereport.ui \
    counter/Reports/complimentarysalesreport.ui \
    counter/Reports/discountsreport.ui \
    customwidgets/test/testform.ui \
    counter/MainScreen/miscellaneousitems.ui \
    counter/Reports/Restaurant/restaurantsalesordersreport.ui \
    counter/Reports/Restaurant/restaurantdeliveryreport.ui \
    counter/Reports/Restaurant/restaurantpendingdelivery.ui \
    counter/Reports/Restaurant/restaurantsaveddrafts.ui \
    counter/Reports/Restaurant/zomatoreport.ui \
    counter/Settings/kotprintersettings.ui \
    counter/Reports/Restaurant/restaurantclosingstock.ui \
    customwidgets/SearchWidgets/Inventoryitem/gmitemsearchlistwidgetlite.ui \
    counter/MainScreen/restaurantitemdetail.ui \
    inventory/masters/sales_inventory_items/salesinventoryopening.ui \
    finance/masters/ledgers/ledgeropeningvalues.ui \
    finance/transactions/BillwiseRecords/addbillwiserecord.ui \
    customwidgets/SearchWidgets/Ledger/gmledgersearchlistwidgetlite.ui \
    customwidgets/LedgersView/ledgersdisplaycontroller.ui

RESOURCES += \
    resources/resources.qrc

SUBDIRS += \
    customwidgets/Material/components/components.pro

DISTFILES += \
    customwidgets/Material/components/icons/LICENSE

